codegen: Update API client to include package docs
awslabs/smithy-go pull request #216
Opened 2020-10-14 18:36 UTC by jasdel

Adds generation of Go package does for API client packages. This takes the API client service model's "description" and uses it as the package doc for the API client package.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-14 21:32 UTC, JordonPhillips requested changes

2020-10-14 21:32 UTC, JordonPhillips commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
> +        Optional<TitleTrait> titleTrait = shape.getTrait(TitleTrait.class);
`return shape.getTrait().map(getvalue).orElse(fallback);`

2020-10-14 21:32 UTC, JordonPhillips commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
> +    private static void writeDocs(CodeWriter writer, Runnable runnable) {
these don't need to be static

2020-10-14 22:31 UTC, JordonPhillips approved these changes

2020-10-15 00:27 UTC, skmcgrail approved these changes

2020-10-15 00:27 UTC, skotambkar approved these changes

2020-10-15 16:54 UTC, merged